test_app/urls.py
from django.urls import path
from . import views

app_name = 'test_app'

urlpatterns = [
    path('create/order/view/', views.create_order_view, name="index"),
    path('order/report/view/', views.get_report_view, name="order_report"),
    path('category/', views.CategoryList.as_view()),
    path('category/<int:pk>/', views.CategoryDetail.as_view()),
    path('category/<int:pk>/add/products/', views.add_product_to_category),
    path('category/<int:pk>/remove/products/', views.remove_product_to_category),
    path('product/', views.ProductList.as_view()),
    path('product/<int:pk>/', views.ProductDetail.as_view()),
    path('order/item/', views.OrderItemList.as_view()),
    path('order/item/<int:pk>/', views.OrderItemDetail.as_view()),
    path('order/', views.OrderList.as_view()),
    path('order/<int:pk>/', views.OrderDetail.as_view()),
    path('order/create/', views.new_order),
    path('order/report/', views.get_report),
]

test_project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from search.views import search

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_app.urls')),
    path('', search, name="order_search")
]

urlpatterns += staticfiles_urlpatterns()

test_app/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    class Meta:
        verbose_name_plural = "Categories"
        verbose_name = "category"

    name = models.CharField(verbose_name="Name", max_length=255)
    products = models.ManyToManyField(verbose_name="Products", to='Product', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name_plural = "Products"
        verbose_name = "product"

    name = models.CharField(verbose_name="Name of product", max_length=255)
    price = models.FloatField(verbose_name="Price", default=0.0)

    def __str__(self):
        return self.name


class Order(models.Model):
    class Meta:
        verbose_name_plural = "Orders"
        verbose_name = "order"

    items = models.ManyToManyField(verbose_name="Items", to='OrderItem')
    date = models.DateField(verbose_name="Order date", default=timezone.now)

    @property
    def total_sum(self):
        t_sum = 0
        for item in self.items.all():
            t_sum += item.order_item_price
        return t_sum

    @property
    def items_indexing(self):
        # Product for indexing. Used in Elasticsearch indexing.
        return [item.product.name for item in self.items.all()]

    def __str__(self):
        return "Order #{}".format(self.pk)


class OrderItem(models.Model):
    class Meta:
        verbose_name_plural = "Order items"
        verbose_name = "order item"

    product = models.ForeignKey(verbose_name="Product", to=Product, on_delete=models.CASCADE)
    quantity = models.FloatField(verbose_name="Quantity", default=0.0)

    @property
    def order_item_price(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name

test_app/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from rest_framework import status
from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from rest_framework.views import APIView

from .serializers import *
from .models import *


class CategoryList(APIView):
    @staticmethod
    def get(request):
        return Response(CategorySerializer(Category.objects.all(), many=True).data)

    @staticmethod
    def post(request):
        serializer = CategorySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CategoryDetail(APIView):
    @staticmethod
    def get_object(pk):
        try:
            return Category.objects.get(pk=pk)
        except Category.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        return Response(CategorySerializer(self.get_object(pk)).data)

    def put(self, request, pk):
        serializer = CategorySerializer(self.get_object(pk), data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        self.get_object(pk).delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ProductList(APIView):
    @staticmethod
    def get(request):
        return Response(ProductSerializer(Product.objects.all(), many=True).data)

    @staticmethod
    def post(request):
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ProductDetail(APIView):
    @staticmethod
    def get_object(pk):
        try:
            return Product.objects.get(pk=pk)
        except Product.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        return Response(ProductSerializer(self.get_object(pk)).data)

    def put(self, request, pk):
        serializer = ProductSerializer(self.get_object(pk), data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        self.get_object(pk).delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class OrderItemList(APIView):
    @staticmethod
    def get(request):
        return Response(OrderItemSerializer(OrderItem.objects.all(), many=True).data)

    def post(self, request):
        serializer = OrderItemSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class OrderItemDetail(APIView):
    @staticmethod
    def get_object(pk):
        try:
            return OrderItem.objects.get(pk=pk)
        except OrderItem.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        return Response(OrderItemSerializer(self.get_object(pk)).data)

    def put(self, request, pk):
        serializer = OrderItemSerializer(self.get_object(pk), data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        self.get_object(pk).delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class OrderList(APIView):
    @staticmethod
    def get(request):
        return Response(OrderSerializer(Order.objects.all(), many=True).data)


class OrderDetail(APIView):
    @staticmethod
    def get_object(pk):
        try:
            return Order.objects.get(pk=pk)
        except Order.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        return Response(OrderSerializer(self.get_object(pk)).data)

    def put(self, request, pk):
        serializer = OrderSerializer(self.get_object(pk), data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        self.get_object(pk).delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['POST'])
def new_order(request):
    order = Order.objects.create()
    order_items = request.data.get("order_items", [])
    for item in order_items:
        if item.get("id", 0) is not 0 or item.get("product", "") is not "":
            order.items.add(
                OrderItem.objects.create(
                    product=Product.objects.create(name=item.get("product", ""),
                                                   price=item.get("price", 0.0)) if item.get("id",
                                                                                             0) is 0 else Product.objects.get(
                        pk=item.get("id", 0)),
                    quantity=item.get("quantity", 0.0)
                )
            )
    if order.items.count() is not 0:
        order.save()
        return Response(OrderSerializer(order).data, status=status.HTTP_201_CREATED)
    else:
        order.delete()
        return Response(status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'POST'])
def add_product_to_category(request, pk):
    if request.method == 'POST':
        product_ids_list = request.data.get("product_ids", [])
        if len(product_ids_list) is not 0 and isinstance(product_ids_list, list):
            category = get_object_or_404(Category, pk=pk)
            for p_id in product_ids_list:
                category.products.add(get_object_or_404(Product, pk=p_id))
            category.save()
            return Response(CategorySerializer(category).data)
        return Response(status=status.HTTP_400_BAD_REQUEST)
    else:
        return Response(CategorySerializer(get_object_or_404(Category, pk=pk)).data)


@api_view(['GET', 'POST'])
def remove_product_to_category(request, pk):
    if request.method == 'POST':
        product_ids_list = request.data.get("product_ids", [])
        if len(product_ids_list) is not 0 and isinstance(product_ids_list, list):
            category = get_object_or_404(Category, pk=pk)
            for p_id in product_ids_list:
                category.products.remove(get_object_or_404(Product, pk=p_id))
            category.save()
            return Response(CategorySerializer(category).data)
        return Response(status=status.HTTP_400_BAD_REQUEST)
    else:
        return Response(CategorySerializer(get_object_or_404(Category, pk=pk)).data)


@api_view(['GET'])
def get_report(request):
    response = {}
    for order in Order.objects.all():
        date = order.date.strftime("%Y-%m-%d")
        if response.get(date, None) is not None:
            response[date] += order.total_sum
        else:
            response[date] = order.total_sum
    return Response(response)


def create_order_view(request):
    return render(request, 'test_app/order_creation.html')


def get_report_view(request):
    return render(request, 'test_app/report.html')

test_app/templates/test_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'search/css/style.css' %}">
    {% block head %}
    {% endblock %}
    <style>
        .menu {
            text-align: left;
            position: fixed;
            display: block;
            overflow: hidden;
            left: 0;
            top: 0;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 60px;
            background-color: black;
        }

        .menu > a {
            position: relative;
            display: inline-block;
            top: 50%;
            transform: translateY(-50%);
            text-decoration: none;
            padding-left: 20px;
        }
    </style>
</head>
<body>
<div class="menu">
    <a href="{% url 'order_search' %}">Search</a>
    <a href="{% url 'test_app:index' %}">Orders</a>
    <a href="{% url 'test_app:order_report' %}">Report</a>
    <a href="/admin/">Admin</a>
</div>
{% block body %}

{% endblock %}
</body>
</html>

test_app/templates/test_app/order_creation.html
{% extends 'test_app/base.html' %}
{% block head %}
    {% load staticfiles %}
    <script src="{% static 'test_app/js/angular.min.js' %}"></script>
    <script src="{% static 'test_app/js/main.js' %}"></script>
    <link rel="stylesheet" href="{% static 'test_app/css/style.css' %}">
{% endblock %}
{% block body %}
    <div ng-app="OrderApp" style="margin-top: 70px">
        {% csrf_token %}
        {% verbatim %}
        <div ng-controller="CreateOrderCtrl">
            <h1 class="title">Select products for new order:</h1>
            <div class="from-list">
                <ul style="list-style-type: none">
                    <li ng-repeat="product in products" ng-click="AddProductToOrder(product)">{{ product.name }}</li>
                </ul>
            </div>
            <div class="to-list" ng-if="selected_products.length > 0">
                <h1 class="title">Edit quantity of products for new order:</h1>
                <table class="tbl-header">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                    </tr>
                    </thead>
                </table>
                <table class="tbl-content">
                    <tbody>
                    <tr ng-repeat="product in selected_products">
                        <td>{{ product.product.name }}</td>
                        <td><input type="number" ng-model="product.quantity"></td>
                        <td><img src="https://cdn1.iconfinder.com/data/icons/mix-color-3/502/Untitled-25-512.png"
                                 width="15px"
                                 height="15px" ng-click="RemoveProductFromOrder(product.product)"></td>
                    </tr>
                    </tbody>
                </table>
                <div class="example_e" align="center" ng-click="order()">Order</div>
            </div>
            <div ng-if="orders.length > 0" style="margin-top: 20px">
                <h1 class="title">Your orders</h1>
                <table class="tbl-header">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Items</th>
                        <th>Total</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                </table>
                <table class="tbl-content">
                    <tbody>
                    <tr ng-repeat="order in orders">
                        <a ng-href="../../order/{{ order.id }}">
                            <td>Order #{{ order.id }}</td>
                            <td>
                                <div ng-repeat="item in order.items">{{ item.product.name }},<span> </span></div>
                            </td>
                            <td>{{ order.total_sum }}</td>
                            <td>{{ order.date }}</td>
                        </a>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        {% endverbatim %}
    </div>
{% endblock %}

test_app/templates/test_app/report.html
{% extends 'test_app/base.html' %}
{% block head %}
    {% load staticfiles %}
    <script src="{% static 'test_app/js/angular.min.js' %}"></script>
    <script src="{% static 'test_app/js/report.js' %}"></script>
    <style>
        .title {
            color: snow;
            font-size: 20px;
            font-weight: bold;
            text-align: left;
        }
    </style>
{% endblock %}
{% block body %}
    {% verbatim %}
    <div ng-app="ReportApp">
        <div ng-controller="ReportCtrl" style="margin-top: 70px">
            <h1 class="title">Your orders:</h1>
            <table class="tbl-header">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Price</th>
                </tr>
                </thead>
            </table>
            <table class="tbl-content">
                <tbody>
                <tr ng-repeat="(key,value) in report_items">
                    <td>{{ key }}</td>
                    <td>{{ value }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endverbatim %}
{% endblock %}